[package]
name = "v4-errors"
version = "0.1.0"
edition = "2024"
autobins = false

[dependencies]
tokio.workspace = true
reqwest.workspace = true
serde_json.workspace = true
axum.workspace = true
futures-util.workspace = true

[[bin]]
name = "v4-server"
path = "src/bin/server.rs"

[[bin]]
name = "v4-client"
path = "src/bin/client.rs"
